[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solpayflex = "vjVYwt9ssMraEBQhbzfNr4bmdLvNN87inq4NSN9ai9J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shivankkapur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
